---

# Add key
- apt_key: url=https://get.docker.io/gpg state=present

# Add repo
- apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

# Update the cache
- apt: update_cache=yes

# Install Docker
- apt: pkg=lxc-docker state=installed

# Make sure it's running.
- service: name=docker state=started

# Remove configuration file.
- command: rm -f /etc/init/docker.conf

# Install proper configuration file.
- get_url: url=https://raw.github.com/octohost/octohost/master/config/docker.conf dest=/etc/init/docker.conf mode=0644

# Make sure it's running.
- service: name=docker state=restarted