---

- name: Add the Docker GPG key.
  apt_key: url=https://get.docker.io/gpg state=present

- name: Add the Docker APT repo.
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: Update APT cache again.
  apt: update_cache=yes

- name: Install Docker.
  apt: pkg=lxc-docker state=installed

- name: Make sure it's running.
  service: name=docker state=started

- name: Remove the existing configuration file.
  command: rm -f /etc/init/docker.conf

- name: Install our configuration file.
  get_url: url=https://raw.github.com/octohost/octohost/master/config/docker.conf dest=/etc/init/docker.conf mode=0644

- name: Restart docker.
  service: name=docker state=restarted

- name: Pull npm-proxy-cache from Docker Index.
  command: docker pull octohost/npm-proxy-cache

- name: Run npm-proxy-cache on 8080
  command: docker run -d -p 8080:8080 octohost/npm-proxy-cache